# [[plugins]]
# https://github.com/preservim/nerdtree
# repo = 'scrooloose/nerdtree'
# hook_add = '''
# autocmd StdinReadPre * let s:std_in=1
# autocmd VimEnter * if argc() == 0 && !exists("s:std_in") | NERDTree | endif
# autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree()) | q | endif
# let g:NERDTreeDirArrowExpandable = '▸'
# let g:NERDTreeDirArrowCollapsible = '▾'
# map <C-e> :NERDTreeToggle<CR>
# '''

[[plugins]]
repo = "itchyny/lightline.vim"

